spring.application.name=login-utils-mgr
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/login_components
spring.datasource.username=root
spring.datasource.password=password

mybatis-plus.mapper-locations=classpath*:org/loginutils/dal/mappers/*.xml
mybatis-plus.type-aliases-package=org.loginutils.dal.model

spring.data.redis.host=localhost
spring.data.redis.port=6379

system.mgr.data=R20260312
system.mgr.version=v2.0.0
