spring.application.name=login-utils-mgr
server.port=8081

#spring.datasource.url=jdbc:mysql://localhost:3306/login_components
spring.datasource.url=jdbc:mysql://100.93.200.127:3306/login_components
spring.datasource.username=root
spring.datasource.password=password

mybatis-plus.mapper-locations=classpath*:org/loginutils/dal/mappers/*.xml
mybatis-plus.type-aliases-package=org.loginutils.dal.model

spring.data.redis.host=localhost
spring.data.redis.port=6379

# ??????? (? Gmail ??)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kai.dev.workmail@gmail.com
#spring.mail.username=test@gmail.com
# ??????????????????(??????)
spring.mail.password=giku wyph vweo fqlg
#spring.mail.password=test
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

system.mgr.data=R20260312
system.mgr.version=v2.0.0
