spring.application.name=login-utils-mgr
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/login_components
spring.datasource.username=root
spring.datasource.password=password

mybatis.mapper-locations=classpath*:org/loginutils/dal/mappers/*.xml
mybatis.type-aliases-package=org.loginutils.dal.model
